version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "agricola-score-local"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-XXXXXXXXXXXX"
s3_prefix = "agricola-score-local"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.build]
[default.build.parameters]
cached = true
parallel = true
